doc: use .env file
idea2app/Strapi-PNPM-Docker-ts pull request #6
Opened 2024-01-13 15:41 UTC by luojiyin1987

update Doc: use .env file
- Closes #5

2024-01-13 15:42 UTC, luojiyin1987 commented
@TechQuery  已经提交 pr

2024-01-13 21:27 UTC, TechQuery requested changes

2024-01-13 21:27 UTC, TechQuery commented on README.md
> +cp .env.example .env ## change .env by yourself
```suggestion
cp .env.example .env  # change .env by yourself
```

2024-01-14 01:48 UTC, TechQuery approved these changes

2024-01-14 01:48 UTC, merged